name: Send Weather and Financial Data

on:
  schedule:
    - cron: '0 */7 * * *'  # Run every 7 hours
  workflow_dispatch:
jobs:
  send_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pytz python-telegram-bot==13.7 forex-python

    - name: Run Python script
      run: python script.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        CITY: ${{ secrets.CITY_WEATHER }}  # Replace with your city
